/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flix.frames;

import flix.model.Filme;

import javax.swing.*;

import static flix.Main.usuario;
import static flix.util.DbManager.avaliar;
import static flix.util.Manager.*;

/**
 *
 * @author Gago3
 */
public class Avaliar extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public Avaliar() {
        super("(Usuário: " + usuario.getNome() + " ) MyImagePro - Catálogo de filmes");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nomeF = new javax.swing.JTextField();
        notaF = new javax.swing.JFormattedTextField();
        nota1 = new javax.swing.JLabel();
        nota2 = new javax.swing.JLabel();
        avaliarB = new javax.swing.JButton();
        procurarB = new javax.swing.JButton();
        filmesCB = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(icon(this.getClass()));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.png"))); // NOI18N
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeF.setBorder(null);
        jPanel2.add(nomeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 230, 30));

        notaF.setBorder(null);
        notaF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        notaF.setToolTipText("8.1");
        jPanel2.add(notaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 50, -1));

        nota1.setText(".");
        jPanel2.add(nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 30, -1));

        nota2.setText(".");
        jPanel2.add(nota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 30, -1));

        avaliarB.setBorderPainted(false);
        avaliarB.setContentAreaFilled(false);
        avaliarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarBActionPerformed(evt);
            }
        });
        jPanel2.add(avaliarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, 60));

        procurarB.setBorderPainted(false);
        procurarB.setContentAreaFilled(false);
        procurarB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        procurarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarBActionPerformed(evt);
            }
        });
        jPanel2.add(procurarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 90, 40));

        filmesCB.setModel(new javax.swing.DefaultComboBoxModel<>(filmes(null)));
        filmesCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmesCBMouseClicked(evt);
            }
        });
        jPanel2.add(filmesCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 420, 340));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbb2 avaliar.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void avaliarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarBActionPerformed
        double nota = Double.parseDouble(notaF.getText().replace(",", "."));
        String nome = filmesCB.getSelectedItem().toString();
        if (avaliar(filme(nome), nota))
            JOptionPane.showMessageDialog(null, "Nota " + nota + " cadastrada");
        else JOptionPane.showMessageDialog(null, "erro");
    }//GEN-LAST:event_avaliarBActionPerformed

    private void procurarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarBActionPerformed
        filmesCB.setModel(new javax.swing.DefaultComboBoxModel<>(filmes(nomeF.getText())));
    }//GEN-LAST:event_procurarBActionPerformed

    private void filmesCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmesCBMouseClicked
        Filme a = filme(filmesCB.getSelectedItem().toString());
        if (a !=null) {
            nota1.setText(String.valueOf(a.getNota_IMDB()));
            nota2.setText(String.valueOf(a.getNota()));
        }
    }//GEN-LAST:event_filmesCBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avaliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avaliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avaliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avaliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Avaliar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarB;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> filmesCB;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nomeF;
    private javax.swing.JLabel nota1;
    private javax.swing.JLabel nota2;
    private javax.swing.JFormattedTextField notaF;
    private javax.swing.JButton procurarB;
    // End of variables declaration//GEN-END:variables
}
