/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flix.frames;

import com.formdev.flatlaf.FlatLightLaf;
import flix.enums.GeneroFilme;

import javax.swing.*;

import static flix.Main.usuario;
import static flix.util.DbManager.registrarFilme;
import static flix.util.Manager.getE;
import static flix.util.Manager.icon;

/**
 *
 * @author Gago3
 */
public class CadFilme extends javax.swing.JFrame {

    /**
     * Creates new form CadFilme
     */
    public CadFilme() {
        super("(Usuário: " + usuario.getNome() + ") MyImagePro - Cadastro de filmes");
        FlatLightLaf.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nomeF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sinopseF = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        capaF = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        iconF = new javax.swing.JTextArea();
        anoF = new javax.swing.JFormattedTextField();
        kidB = new javax.swing.JCheckBox();
        notaF = new javax.swing.JFormattedTextField();
        classCB = new javax.swing.JComboBox<>();
        genCB2 = new javax.swing.JComboBox<>();
        genCB1 = new javax.swing.JComboBox<>();
        cadastrarB = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setIconImage(icon(this.getClass()));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/others/icon2.png"))); // NOI18N
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeF.setText("Velozes e furiosos");
        nomeF.setToolTipText("");
        nomeF.setBorder(null);
        nomeF.setMaximumSize(new java.awt.Dimension(220, 50));
        nomeF.setMinimumSize(new java.awt.Dimension(220, 50));
        nomeF.setPreferredSize(new java.awt.Dimension(220, 50));
        jPanel1.add(nomeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 280, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 150));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 150));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 150));

        sinopseF.setColumns(20);
        sinopseF.setLineWrap(true);
        sinopseF.setRows(5);
        sinopseF.setText("Um policial de Los Angeles, deverá decidir onde fica sua lealdade quando se apaixona pelo mundo que teve que destruir.\n");
        sinopseF.setToolTipText("");
        sinopseF.setBorder(null);
        sinopseF.setCaretPosition(0);
        sinopseF.setMaximumSize(new java.awt.Dimension(250, 100));
        sinopseF.setMinimumSize(new java.awt.Dimension(250, 100));
        sinopseF.setPreferredSize(new java.awt.Dimension(250, 100));
        jScrollPane1.setViewportView(sinopseF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 710, 130));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(440, 60));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(440, 60));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(440, 60));

        capaF.setColumns(20);
        capaF.setLineWrap(true);
        capaF.setRows(5);
        capaF.setToolTipText("");
        capaF.setBorder(null);
        capaF.setMaximumSize(new java.awt.Dimension(440, 60));
        capaF.setMinimumSize(new java.awt.Dimension(440, 60));
        jScrollPane2.setViewportView(capaF);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 710, 30));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(440, 60));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(440, 60));
        jScrollPane3.setOpaque(false);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(440, 60));

        iconF.setColumns(20);
        iconF.setLineWrap(true);
        iconF.setRows(5);
        iconF.setToolTipText("");
        iconF.setBorder(null);
        jScrollPane3.setViewportView(iconF);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 710, 30));

        anoF.setBorder(null);
        anoF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY"))));
        anoF.setToolTipText("");
        anoF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        anoF.setMaximumSize(new java.awt.Dimension(130, 40));
        anoF.setMinimumSize(new java.awt.Dimension(130, 40));
        anoF.setPreferredSize(new java.awt.Dimension(130, 40));
        anoF.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(anoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 110, 30));
        jPanel1.add(kidB, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 110, 40));

        notaF.setBorder(null);
        notaF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.0"))));
        notaF.setToolTipText("");
        notaF.setMinimumSize(new java.awt.Dimension(105, 40));
        notaF.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel1.add(notaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 110, 30));

        classCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10+", "12+", "14+", "16+", "18+" }));
        classCB.setToolTipText("");
        classCB.setBorder(null);
        classCB.setMaximumSize(new java.awt.Dimension(125, 50));
        classCB.setMinimumSize(new java.awt.Dimension(125, 50));
        classCB.setPreferredSize(new java.awt.Dimension(125, 50));
        jPanel1.add(classCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, -1, 30));

        genCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Comédia", "Romance", "Suspense", "Terror" }));
        genCB2.setBorder(null);
        jPanel1.add(genCB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 90, 30));

        genCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Comédia", "Romance", "Suspense", "Terror" }));
        genCB1.setBorder(null);
        genCB1.setMaximumSize(new java.awt.Dimension(92, 43));
        jPanel1.add(genCB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 90, 30));

        cadastrarB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarB.setBorderPainted(false);
        cadastrarB.setContentAreaFilled(false);
        cadastrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 650));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/bbb2 cadfilme.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBActionPerformed
        if (nomeF.getText().equals("") || anoF.getText().equals("") || notaF.getText().equals("") || sinopseF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Há campos não preenchidos.");
            return;
        }
        GeneroFilme a1 = (GeneroFilme) getE(genCB1.getSelectedItem().toString()), a2 = (GeneroFilme) getE(genCB1.getSelectedItem().toString());
        if (registrarFilme(usuario, nomeF.getText(), sinopseF.getText(), capaF.getText(), iconF.getText(), Integer.parseInt(anoF.getText()), Double.parseDouble(notaF.getText().replace(",", ".")), classCB.getSelectedItem().toString(), kidB.isSelected(), a1, a2)) {
            JOptionPane.showMessageDialog(null, "Filme <" + nomeF.getText() +  "> cadastrado com sucesso!");
            dispose();
            new Avaliar().setVisible(true);
        } else JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o filme!");
    }//GEN-LAST:event_cadastrarBActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadFilme().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField anoF;
    private javax.swing.JLabel background;
    private javax.swing.JButton cadastrarB;
    private javax.swing.JTextArea capaF;
    private javax.swing.JComboBox<String> classCB;
    private javax.swing.JComboBox<String> genCB1;
    private javax.swing.JComboBox<String> genCB2;
    private javax.swing.JTextArea iconF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox kidB;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nomeF;
    private javax.swing.JFormattedTextField notaF;
    private javax.swing.JTextArea sinopseF;
    // End of variables declaration//GEN-END:variables
}