/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flix.frames;

import flix.enums.Genero;
import flix.enums.GeneroFilme;

import javax.swing.*;
import java.time.LocalDate;

import static flix.Main.usuario;
import static flix.util.DbManager.cadUsuario;
import static flix.util.Manager.*;

/**
 *
 * @author Gago3
 */
public class CadUser extends javax.swing.JFrame {

    /**
     * Creates new form CadFilme
     */
    public CadUser() {
        super("(Usuário: " + usuario.getNome() + " ) MyImagePro - Cadastro de usuário");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeF = new javax.swing.JTextField();
        sobrenomeF = new javax.swing.JTextField();
        cpfF = new javax.swing.JTextField();
        emailF = new javax.swing.JTextField();
        senhaF = new javax.swing.JPasswordField();
        nascimentoF = new javax.swing.JFormattedTextField();
        generoCB = new javax.swing.JComboBox<>();
        cadastroB = new javax.swing.JButton();
        genFav1CB = new javax.swing.JComboBox<>();
        genFav2CB = new javax.swing.JComboBox<>();
        menu = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setIconImage(icon(this.getClass()));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeF.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        jPanel1.add(nomeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, -1));

        sobrenomeF.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobrenome"));
        jPanel1.add(sobrenomeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 160, -1));

        cpfF.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        jPanel1.add(cpfF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, -1));

        emailF.setBorder(javax.swing.BorderFactory.createTitledBorder("email"));
        jPanel1.add(emailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 380, -1));

        senhaF.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        jPanel1.add(senhaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 110, 160, -1));

        nascimentoF.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Nascimento"));
        nascimentoF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanel1.add(nascimentoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 128, -1));

        generoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não-binário", "Masculino", "Feminino" }));
        generoCB.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero"));
        jPanel1.add(generoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 123, -1));

        cadastroB.setText("Cadastrar");
        cadastroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroBActionPerformed(evt);
            }
        });
        jPanel1.add(cadastroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        genFav1CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Comédia", "Romance", "Suspense", "Terror" }));
        genFav1CB.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero favorito 1"));
        genFav1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFav1CBActionPerformed(evt);
            }
        });
        jPanel1.add(genFav1CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 123, -1));

        genFav2CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Comédia", "Romance", "Suspense", "Terror" }));
        genFav2CB.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero favorito 2"));
        jPanel1.add(genFav2CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 128, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 540, 440));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.png"))); // NOI18N
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbb2 cad.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cadastroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroBActionPerformed
        Genero genero = (Genero) getE(generoCB.getSelectedItem().toString());
        GeneroFilme a1 = (GeneroFilme) getE(genFav1CB.getSelectedItem().toString()), a2 = (GeneroFilme) getE(genFav2CB.getSelectedItem().toString());
        String a = nascimentoF.getText();
        if (!cpf(cpfF.getText())) {
            JOptionPane.showMessageDialog(null, "Insira um CPF válido!");
            return;
        }
        int dia = Integer.parseInt(a.substring(0, a.indexOf("/"))),
                mes = Integer.parseInt(a.substring(a.indexOf("/")+1, a.lastIndexOf("/"))),
                ano = Integer.parseInt(a.substring(a.lastIndexOf("/")+1));
        LocalDate ld = LocalDate.of(ano, mes, dia);
        cadUsuario(nomeF.getText(), sobrenomeF.getText(), Long.parseLong(cpfF.getText()), emailF.getText(), new String(senhaF.getPassword()), ld, genero, a1, a2);
    }//GEN-LAST:event_cadastroBActionPerformed

    private void genFav1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFav1CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genFav1CBActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        new MenuAdm().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cadastroB;
    private javax.swing.JTextField cpfF;
    private javax.swing.JTextField emailF;
    private javax.swing.JComboBox<String> genFav1CB;
    private javax.swing.JComboBox<String> genFav2CB;
    private javax.swing.JComboBox<String> generoCB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu;
    private javax.swing.JFormattedTextField nascimentoF;
    private javax.swing.JTextField nomeF;
    private javax.swing.JPasswordField senhaF;
    private javax.swing.JTextField sobrenomeF;
    // End of variables declaration//GEN-END:variables
}
