/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flix.frames;

import javax.swing.*;

import static flix.Main.usuario;
import static flix.util.Manager.icon;

/**
 *
 * @author 823115101
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        super("(Usuário: " + usuario.getNome() + ") MyImagePro - Dashboard");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeL = new javax.swing.JLabel();
        sobrenomeL = new javax.swing.JLabel();
        nascimentoL = new javax.swing.JLabel();
        generoL = new javax.swing.JLabel();
        generoFav1L = new javax.swing.JLabel();
        generoFav2L = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(icon(this.getClass()));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(100, 100, 100));
        jLabel3.setIcon(usuario.getIcon());
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        nomeL.setText(usuario.getNome());
        jPanel1.add(nomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 250, 80));

        sobrenomeL.setText(usuario.getSobrenome());
        jPanel1.add(sobrenomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 260, 80));

        nascimentoL.setText(String.valueOf(usuario.getNascimento()));
        jPanel1.add(nascimentoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, 60));

        generoL.setText(usuario.getGenero().toString());
        jPanel1.add(generoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 200, 60));

        generoFav1L.setText(usuario.getGenero1().toString());
        jPanel1.add(generoFav1L, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        generoFav2L.setText(usuario.getGenero2().toString());
        jPanel1.add(generoFav2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 830, 670));

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.png"))); // NOI18N
        sair.setBorder(null);
        sair.setBorderPainted(false);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 580, -1, -1));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.png"))); // NOI18N
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbb2 catalogo.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        this.dispose();
        usuario = null;
        new Login().setVisible(true);
    }//GEN-LAST:event_sairActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        this.dispose();
        new MenuAdm().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel generoFav1L;
    private javax.swing.JLabel generoFav2L;
    private javax.swing.JLabel generoL;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu;
    private javax.swing.JLabel nascimentoL;
    private javax.swing.JLabel nomeL;
    private javax.swing.JButton sair;
    private javax.swing.JLabel sobrenomeL;
    // End of variables declaration//GEN-END:variables
}
