/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flix.frames;

import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;

import java.time.LocalDate;
import java.time.Period;

import static flix.Main.usuario;
import static flix.util.Manager.icon;

/**
 *
 * @author 823115101
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        super("(Usuário: " + usuario.getNome() + ") MyImagePro - Dashboard");
        FlatLightLaf.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconL = new javax.swing.JLabel();
        nomeL = new javax.swing.JLabel();
        nascimentoL = new javax.swing.JLabel();
        generoL = new javax.swing.JLabel();
        generoFav1L = new javax.swing.JLabel();
        generoFav2L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(icon(this.getClass()));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconL.setBackground(new java.awt.Color(100, 100, 100));
        iconL.setIcon(usuario.getIcon());
        iconL.setMaximumSize(new java.awt.Dimension(200, 200));
        iconL.setMinimumSize(new java.awt.Dimension(200, 200));
        iconL.setOpaque(true);
        iconL.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(iconL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        nomeL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeL.setText(nome());
        jPanel1.add(nomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 470, 30));

        nascimentoL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nascimentoL.setText(idade());
        jPanel1.add(nascimentoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 70, 30));

        generoL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generoL.setText(gen(0));
        jPanel1.add(generoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 120, 30));

        generoFav1L.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generoFav1L.setText(gen(1));
        jPanel1.add(generoFav1L, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 220, 30));

        generoFav2L.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generoFav2L.setText(gen(2));
        jPanel1.add(generoFav2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 220, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText(usuario.getEmail().toString());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 830, 670));

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/others/icon2.png"))); // NOI18N
        sair.setBorder(null);
        sair.setBorderPainted(false);
        sair.setContentAreaFilled(false);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 580, -1, -1));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/others/icon2.png"))); // NOI18N
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/bbb2 perfil.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
        usuario = null;
        new Login().setVisible(true);
    }//GEN-LAST:event_sairActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel generoFav1L;
    private javax.swing.JLabel generoFav2L;
    private javax.swing.JLabel generoL;
    private javax.swing.JLabel iconL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu;
    private javax.swing.JLabel nascimentoL;
    private javax.swing.JLabel nomeL;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables

    public static String gen(int i) {
        switch (i) {
            case 0 -> {
                return usuario.getGenero().nome();
            }
            case 1 -> {
                return usuario.getGenero1().nome();
            }
            case 2 -> {
                return usuario.getGenero2().nome();
            }
        }
        return "erro";
    }
    public static String nome() {
        return usuario.getNome() + " " + usuario.getSobrenome();
    }
    public static String idade() {
        return Period.between(usuario.getNascimento().toLocalDate(), LocalDate.now()).getYears() + " anos";
    }
}
