/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flix.frames;

import javax.swing.*;

import static flix.Main.login;
import static flix.util.DbManager.exists;
import static flix.util.DbManager.logar;
import static flix.util.Manager.icon;
import static flix.util.Manager.nulo;

/**
 *
 * @author Gago3
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        super("(Usuário: " + nulo() + ") MyImagePro - Login");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        loginF = new javax.swing.JTextField();
        passF = new javax.swing.JPasswordField();
        forgetPassB = new javax.swing.JLabel();
        loginB = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(icon(this.getClass()));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("loginFrame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(10, 16, 21));
        panelLogin.setAlignmentX(0.0F);
        panelLogin.setAlignmentY(0.0F);
        panelLogin.setMaximumSize(new java.awt.Dimension(300, 500));
        panelLogin.setOpaque(false);
        panelLogin.setPreferredSize(new java.awt.Dimension(300, 500));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginF.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        loginF.setText("admin");
        loginF.setBorder(null);
        loginF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFActionPerformed(evt);
            }
        });
        panelLogin.add(loginF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 20));

        passF.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        passF.setText("admin");
        passF.setBorder(null);
        passF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFActionPerformed(evt);
            }
        });
        panelLogin.add(passF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, -1));

        forgetPassB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelLogin.add(forgetPassB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, 20));

        loginB.setBorderPainted(false);
        loginB.setContentAreaFilled(false);
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });
        panelLogin.add(loginB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 140, 60));

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 290, 290));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbb2 login.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void loginFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFActionPerformed

    private void passFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        String nome = loginF.getText();
        String senha = new String(passF.getPassword());
        if (!exists(nome)) JOptionPane.showMessageDialog(null, "Usuário não existe.");
        else if (!logar(nome, senha)) JOptionPane.showMessageDialog(null, "Senha inválida.");
        else try {
                login(nome, senha);
                if (nome.equals("admin"))
                    new MenuAdm().setVisible(true);
                else new Menu().setVisible(true);
                dispose();
                JOptionPane.showMessageDialog(null, "Logado com sucesso!");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválida!");
            }
    }//GEN-LAST:event_loginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel forgetPassB;
    private javax.swing.JButton loginB;
    private javax.swing.JTextField loginF;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField passF;
    // End of variables declaration//GEN-END:variables
}
