/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flix.frames;

import flix.Main;

import javax.swing.*;

import static flix.Main.usuario;
import static flix.util.Manager.icon;

/**
 *
 * @author 823115101
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        super("(Usuário: " + usuario.getNome() + ") MyImagePro - Menu");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuP = new javax.swing.JPanel();
        catalogoB = new javax.swing.JButton();
        cadFilmeB = new javax.swing.JButton();
        dashboardB = new javax.swing.JButton();
        avaliarB = new javax.swing.JButton();
        catalogoF = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(icon(this.getClass()));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuP.setOpaque(false);
        menuP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        catalogoB.setBorderPainted(false);
        catalogoB.setContentAreaFilled(false);
        catalogoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoBActionPerformed(evt);
            }
        });
        menuP.add(catalogoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 30));

        cadFilmeB.setBorderPainted(false);
        cadFilmeB.setContentAreaFilled(false);
        cadFilmeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFilmeBActionPerformed(evt);
            }
        });
        menuP.add(cadFilmeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 40));

        dashboardB.setBorderPainted(false);
        dashboardB.setContentAreaFilled(false);
        dashboardB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBActionPerformed(evt);
            }
        });
        menuP.add(dashboardB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, 40));

        avaliarB.setBorderPainted(false);
        avaliarB.setContentAreaFilled(false);
        avaliarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarBActionPerformed(evt);
            }
        });
        menuP.add(avaliarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, 40));
        menuP.add(catalogoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 130, 50));

        getContentPane().add(menuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 420, 340));

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.png"))); // NOI18N
        sair.setBorder(null);
        sair.setBorderPainted(false);
        sair.setContentAreaFilled(false);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 580, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbb2 menu.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catalogoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoBActionPerformed
        dispose();
        new Filmes().setVisible(true);
    }//GEN-LAST:event_catalogoBActionPerformed

    private void cadFilmeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFilmeBActionPerformed
        dispose();
        new CadFilme().setVisible(true);
    }//GEN-LAST:event_cadFilmeBActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
        Main.usuario = null;
        new Login().setVisible(true);
    }//GEN-LAST:event_sairActionPerformed

    private void dashboardBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBActionPerformed
        dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_dashboardBActionPerformed

    private void avaliarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarBActionPerformed
        dispose();
        new Avaliar().setVisible(true);
    }//GEN-LAST:event_avaliarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarB;
    private javax.swing.JLabel background;
    private javax.swing.JButton cadFilmeB;
    private javax.swing.JButton catalogoB;
    private javax.swing.JLabel catalogoF;
    private javax.swing.JButton dashboardB;
    private javax.swing.JPanel menuP;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
