/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flix.frames;

import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;

import static flix.Main.usuario;
import static flix.util.Manager.getUsuarios;
import static flix.util.Manager.icon;

/**
 *
 * @author Gago3
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public Usuarios() {
        super("(Usuário: " + usuario.getNome() + " ) MyImagePro - Gerenciamento de usuários");
        FlatLightLaf.setup();
        initComponents();
        usuariosT.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosT = new javax.swing.JTable();
        nomeF = new javax.swing.JTextField();
        emailF = new javax.swing.JTextField();
        filtrarB = new javax.swing.JButton();
        limparB = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(icon(this.getClass()));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/others/icon2.png"))); // NOI18N
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuariosT.setAutoCreateRowSorter(true);
        usuariosT.setModel(new javax.swing.table.DefaultTableModel(
            getUsuarios(null, null),
            new String [] {
                "Nome", "Sobrenome", "CPF", "Email", "Idade", "Gênero", "Gênero1 fav", "Gênero2 fav", "Admin"
            }
        ));
        usuariosT.setToolTipText("");
        usuariosT.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        usuariosT.setColumnSelectionAllowed(true);
        usuariosT.setDoubleBuffered(true);
        usuariosT.setEnabled(false);
        usuariosT.setFocusable(false);
        usuariosT.setName(""); // NOI18N
        usuariosT.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(usuariosT);
        resizeColumns();

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 830, 540));

        nomeF.setToolTipText("");
        nomeF.setBorder(null);
        nomeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFActionPerformed(evt);
            }
        });
        jPanel2.add(nomeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, 30));

        emailF.setToolTipText("");
        emailF.setBorder(null);
        emailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFActionPerformed(evt);
            }
        });
        jPanel2.add(emailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 470, 30));

        filtrarB.setBorder(null);
        filtrarB.setContentAreaFilled(false);
        filtrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarBActionPerformed(evt);
            }
        });
        jPanel2.add(filtrarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 90, 40));

        limparB.setBorder(null);
        limparB.setContentAreaFilled(false);
        limparB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBActionPerformed(evt);
            }
        });
        jPanel2.add(limparB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 100, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 650));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/bbb2 usuarios.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        new MenuAdm().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void filtrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarBActionPerformed
        filtro();
    }//GEN-LAST:event_filtrarBActionPerformed

    private void limparBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBActionPerformed
        nomeF.setText("");
        emailF.setText("");
        usuariosT.setModel(new javax.swing.table.DefaultTableModel(
                getUsuarios(null, null),
                new String[]{
                        "Nome", "Sobrenome", "CPF", "Email", "Idade", "Gênero", "Gênero1 fav", "Gênero2 fav", "Admin"
                }));
    }//GEN-LAST:event_limparBActionPerformed

    private void nomeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFActionPerformed
        filtro();
    }//GEN-LAST:event_nomeFActionPerformed

    private void emailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFActionPerformed
        filtro();
    }//GEN-LAST:event_emailFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField emailF;
    private javax.swing.JButton filtrarB;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparB;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nomeF;
    private javax.swing.JTable usuariosT;
    // End of variables declaration//GEN-END:variables
    private void filtro() {
        if (nomeF.getText().equals("") && emailF.getText().equals("")) usuariosT.setModel(new javax.swing.table.DefaultTableModel(
                getUsuarios(null, null),
                new String[]{
                        "Nome", "Sobrenome", "CPF", "Email", "Idade", "Gênero", "Gênero1 fav", "Gênero2 fav", "Admin"
                }
        ));
        else usuariosT.setModel(new javax.swing.table.DefaultTableModel(
                getUsuarios(nomeF.getText(), emailF.getText()),
                new String[]{
                        "Nome", "Sobrenome", "CPF", "Email", "Idade", "Gênero", "Gênero1 fav", "Gênero2 fav", "Admin"
                }
        ));
    }
    private void resizeColumns() {
        for (int i=0; i<usuariosT.getColumnCount(); i++)
            usuariosT.getColumnModel().getColumn(i).sizeWidthToFit();
    }
}
